### PR TITLE
fix(paths): move internal paths on a different port

### LINKED ISSUE #1872: /metrics endpoint shouldn't be exposed on the same port as jimm's service
right now we have the `/metrics` endpoint exposed on the same port as JIMM, this is an issue because when an ingress is created for jimm it exposes the metrics endpoints as well.

### PR DESCRIPTION
**Pull request by SimoneDutto**
## Description
Move internal paths under a different path.

> fly by increase ReadTimeout

Fix: #1872
## QA

`make dev-env`

Visit:
`http://jimm.localhost:17090/debug/status`
`http://jimm.localhost:17090/metrics`

### CODE REVIEW

File: cmd/jimmsrv/service/service.go [hunk 1]
```diff
@@ -660,6 +649,28 @@ func NewServiceFromDependencies(ctx context.Context, deps *ServiceDependencies)
...
 }
 
+// NewInternalService builds the internal-only HTTP server serving /metrics and /debug.
+func NewInternalService(addr string, corsAllowedOrigins []string) *http.Server {
+	mux := chi.NewRouter()
+	corsOpts := cors.New(cors.Options{
+		AllowedOrigins:   corsAllowedOrigins,
+		AllowedMethods:   []string{"GET"},
+		AllowCredentials: true,
+	})
```
Comment (kian99) [inline cmd/jimmsrv/service/service.go:659]: We don't need to worry about CORS for these endpoints unless we think the dashboard is going to request them.

File: cmd/jimmsrv/service/service.go [hunk 2]
```diff
@@ -660,6 +649,28 @@ func NewServiceFromDependencies(ctx context.Context, deps *ServiceDependencies)
 	return s, nil
 }
 
+// NewInternalService builds the internal-only HTTP server serving /metrics and /debug.
```
Comment (ale8k) [inline cmd/jimmsrv/service/service.go]: Don't put /metrics and /debug in godoc as it is likely subject to add more

File: cmd/jimmsrv/main.go [hunk 3]
```diff
@@ -187,6 +187,12 @@ func start(ctx context.Context, s *service.Service) error {
 		}
 	}
 
+	internalAddr := os.Getenv("JIMM_INTERNAL_LISTEN_ADDR")
+	if internalAddr == "" {
+		internalAddr = ":9090"
```
Comment (ale8k) [inline cmd/jimmsrv/main.go:192]: Prometheus default is 9090 isn't it? Maybe use 8080?

File: cmd/jimmsrv/main.go [hunk 4]
```diff
@@ -246,7 +252,7 @@ func start(ctx context.Context, s *service.Service) error {
 	httpsrv := &http.Server{
 		Addr:              addr,
 		Handler:           jimmsvc,
-		ReadHeaderTimeout: time.Second * 5,
+		ReadHeaderTimeout: time.Second * 30,
```
Comment (ale8k) [inline cmd/jimmsrv/main.go:255]: I think we can remove this possibly. I don't remember why I added it but I'm not worried?

**Review by ale8k — APPROVED** [review]
Some minor comments, but lgtm, nice!

File: cmd/jimmsrv/main.go (hunk 3 above)
Comment (SimoneDutto) [reply cmd/jimmsrv/main.go:192]: it doesn't matter anyways because we are mapping this port in docker, and in the charm

File: cmd/jimmsrv/main.go (hunk 4 above)
Comment (SimoneDutto) [reply cmd/jimmsrv/main.go:255]: if you remove it:
```
[10:38:02] ➜  jimm git:(separate-internal-paths) ✗ golangci-lint run      
cmd/jimmsrv/main.go:252:14: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
        httpsrv := &http.Server{
                Addr:    addr,
                Handler: jimmsvc,
        }
1 issues:
* gosec: 1
```

**Review by luci1900 — APPROVED** [review]
I'm not entirely convinced the separate port is necessary, but even just the separation of all internal paths registered in one place is useful.

File: cmd/jimmsrv/service/service.go (hunk 1 above)
Comment (SimoneDutto) [reply cmd/jimmsrv/service/service.go:659]: i've added it because they might need to ask for the version or something to show on the dashboard is already there
